#!/bin/sh -e
# shellcheck source=/dev/null

if [ "$(whoami)" != "root" ]; then printf "This script need to run as root.\n" && exit 1; fi

# load functions and config
. scripts/functions
. ./config

cd rootfs

find root/ -maxdepth 1 -name ".*" -type f -exec rm {} \; -print

rm -rf etc/apk
rm -rf etc/lvm
rm -rf etc/init.d
rm -rf etc/skel
rm -rf etc/conf.d
rm -rf etc/crontabs
rm -rf etc/logrotate.d
rm -rf etc/modules-load.d
rm -rf etc/opt
rm -rf etc/periodic
rm -rf etc/secfixes.d
rm -rf etc/sysctl.d

rm -rf etc/shadow.apk-new
rm -rf etc/vdpau_wrapper.cfg
rm -rf etc/resolv.conf
rm -rf etc/inittab
rm -rf etc/pkcs11

rm -rf lib/firmware
rm -rf lib/pkgconfig
rm -rf lib/mdev
rm -rf lib/apk
rm -rf lib/modules-load.d
rm -rf lib/sysctl.d

rm -rf sbin/apk

rm -rf usr/lib/libva*
rm -rf usr/lib/libvd*
rm -rf usr/lib/libLLVM*
rm -rf usr/lib/libGL*
rm -rf usr/lib/libdrm_exynos*
rm -rf usr/lib/libdrm_etnaviv*
rm -rf usr/lib/libdrm_freedreno*
rm -rf usr/lib/libdrm_tegra*

rm -rf usr/lib/pkcs11
rm -rf usr/lib/modules-load.d
rm -rf usr/lib/llvm13
rm -rf usr/lib/pkgconfig
rm -rf usr/lib/udev
rm -rf usr/lib/vdpau
rm -rf usr/lib/dri
rm -rf usr/lib/xorg/modules/dri

rm -rf usr/local

rm -rf usr/share/apk-tools
rm -rf usr/share/appdata
rm -rf usr/share/devhelp
rm -rf usr/share/gtk-doc
rm -rf usr/share/doc
rm -rf usr/share/aclocal
rm -rf usr/share/drirc.d
rm -rf usr/share/licenses
rm -rf usr/share/misc
rm -rf usr/share/pkgconfig
rm -rf usr/share/polkit-1
rm -rf usr/share/p11-kit
rm -rf usr/share/util-macros
rm -rf usr/share/vulkan
rm -rf usr/share/apk
rm -rf usr/share/man
rm -rf usr/share/xml
rm -rf usr/share/slsh
rm -rf usr/share/themes/Raleigh
